name: Deploy NPM Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-n-publish:
    name: Build and publish Steamship to NPM
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run test:unit
      - run: reset-hard
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
