name: Test

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging

jobs:
  test:
    name: Run test suite
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Python (faster than using Python container)
      - name: Setup Project
        run: |
          npm install
      - name: Run test suite (Steamship Prod)
        run: npm run test:unit
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          STEAMSHIP_API_KEY: ${{ secrets.STEAMSHIP_PROD_TEST_KEY }}
          STEAMSHIP_API_BASE: ${{ secrets.STEAMSHIP_PROD_TEST_API_BASE }}
          STEAMSHIP_APP_BASE: ${{ secrets.STEAMSHIP_PROD_TEST_APP_BASE }}
      - name: Run test suite (Steamship Staging)
        run: npm run test:unit
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          STEAMSHIP_API_KEY: ${{ secrets.STEAMSHIP_STAGING_API_KEY }}
          STEAMSHIP_API_BASE: ${{ secrets.STEAMSHIP_STAGING_TEST_API_BASE }}
          STEAMSHIP_APP_BASE: ${{ secrets.STEAMSHIP_STAGING_TEST_APP_BASE }}
